### ISSUE TITLE
Blatant Copy.

### ISSUE THREAD

**Issue by AriaFallah** [caspervonb/codeless#2]
https://github.com/kelseyhightower/nocode

**Comment by caspervonb** [comment]
See https://github.com/kelseyhightower/nocode/issues/2392

We wish the maintainers of No Code the best of luck and give a huge thanks for all the research in this exciting field of hyper efficient computing.

However we believe Codeless to be a better solution all around, it has more solid technology behind it and No Code is just not keeping up with it's pull requests.

**Comment by caspervonb** [comment]
FYI Clientless, the predecessor of Codeless actually predates No Code, work started back in 2017 https://twitter.com/caspervonb/status/931989024381665280
