### ISSUE TITLE
Lacks a one-pager architecture overview diagram

### ISSUE THREAD

**Issue by noln** [caspervonb/codeless#6]
We're using this for a new project, and one of the PMs (the one with the hair that looks like a wig) is asking for an overview diagram he can put in his slide deck.

Preferably with the only author attribution being top or bottom edge, so it's easier to crop out and replace with his name.

**Comment by TheGuywithTheHat** [comment]
This is what I've been able to gather, but I could be overthinking it:

![codeless architecture diagram](https://i.imgur.com/UfHwEIt.png)
