### ISSUE TITLE
I'm also a teapot.

### ISSUE THREAD

**Issue by BytewaveMLP** [caspervonb/codeless#7]
This is literally just [nocode](https://github.com/kelseyhightower/nocode) with a different project title. If you're gonna make a joke, at least keep it original or give credit, jeez.

**Comment by BytewaveMLP** [comment]
Hm. This appears to have been addressed in #2.
I still don't like it, though.

**Comment by caspervonb** [comment]
First of all, this project is no joke it is the future.

If you're really going to go there: the original is Clientless https://twitter.com/caspervonb/status/931989024381665280

We just have other goals than No Code.
